version: "3.8"
 
services: 
  postgres:
    container_name: postgres-con
    image: postgres:13
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "database_development"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
 
  backend:
    build:
      context: ./backend
    container_name: backend-app
    environment:
      DEV_DB_USERNAME: "root"
      DEV_DB_PASSWORD: "root"
      DB_HOSTNAME: "postgres"
    ports:
      - "3001:3001"
    networks:
      - my-net
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "sleep 10 && node index.js"]
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://backend-app:3001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
 
  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - "80:80"
    networks:
      - my-net
    restart: always
    depends_on:
      - backend
 
volumes:
  pgdata:
 
networks:
  my-net:
