apiVersion: v1
kind: Service
metadata:
  name: conduit-db-svc
  namespace: conduit-ns
spec:
  selector:
    app: conduit-postgres 
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None

