apiVersion: v1
kind: Service
metadata:
  name: conduit-backend-svc
  labels:
    app: conduit-backend-svc
  namespace: conduit-ns
spec:
  selector:
    app: conduit-backend-pod
  type: NodePort
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
