apiVersion: v1
kind: Service
metadata:
  name: conduit-frontend-svc
  labels:
    app: conduit-frontend-svc
  namespace: conduit-ns
spec:
  selector:
    app: conduit-frontend-pod
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080  # Choose an available port in the NodePort range (30000-32767)
